CREATE TABLE PERSON(
  PERSON_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(64) NOT NULL,
  LAST_NAME VARCHAR(64) NOT NULL,
  EMAIL_ADDRESS VARCHAR(128) NOT NULL
);

CREATE TABLE ITEM(
  ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(256),
  MANUFACTURER VARCHAR(128),
  MODEL VARCHAR(64),
  QUANTITY INT DEFAULT 1,
  PERSON_ID BIGINT NOT NULL,
);

ALTER TABLE ITEM ADD FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID);

